from pydantic import BaseModel


class RevisionRequest(BaseModel):
    """
    Feedback generated by the review layer.

    This object tells the Architecture Agent
    exactly what should be improved.
    """

    feedback: list[str]

    previous_recommendation: str

    score: int
